# Generated by Django 4.2.11 on 2024-05-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_rename_order_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
