# Generated by Django 4.2.11 on 2024-05-26 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist', '0014_alter_placeinfo_options_placeinfo_address_and_more'),
        ('basket', '0007_rename_orders_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='session',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='dishe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishlist.dishes', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterModelTable(
            name='basketitem',
            table='cart',
        ),
    ]
