# Generated by Django 4.2.11 on 2024-05-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_alter_basketitem_options_remove_basketitem_session_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basketitem',
            table='basket',
        ),
    ]
