# Generated by Django 4.2.11 on 2024-05-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('basket', '0009_alter_basketitem_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='session_key',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
